//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeSheet.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveTasks {
            get {
                return ResourceManager.GetString("ActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the active tasks.
        /// </summary>
        public static string ActiveTasksCheckBoxMessage {
            get {
                return ResourceManager.GetString("ActiveTasksCheckBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds 10 minutes to the duration.
        /// </summary>
        public static string Add10MinToDuration {
            get {
                return ResourceManager.GetString("Add10MinToDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company2 doesn&apos;t match with Company!.
        /// </summary>
        public static string CompanyName2DoesntMatch {
            get {
                return ResourceManager.GetString("CompanyName2DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company2&apos;s name is empty!.
        /// </summary>
        public static string CompanyName2IsEmpty {
            get {
                return ResourceManager.GetString("CompanyName2IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s name is empty!.
        /// </summary>
        public static string CompanyNameIsEmpty {
            get {
                return ResourceManager.GetString("CompanyNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s name have to reach minimum 10 characters and also can&apos;t be more than 60!.
        /// </summary>
        public static string CompanyNameWrongLength {
            get {
                return ResourceManager.GetString("CompanyNameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new record.
        /// </summary>
        public static string CreateNewRecord {
            get {
                return ResourceManager.GetString("CreateNewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new task.
        /// </summary>
        public static string CreateNewTask {
            get {
                return ResourceManager.GetString("CreateNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record&apos;s date can&apos;t be in the future!.
        /// </summary>
        public static string DateCantBeInFuture {
            get {
                return ResourceManager.GetString("DateCantBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record&apos;s date can&apos;t be earlier than the date when the task was created!.
        /// </summary>
        public static string DateCantBePastTheTaskCreationDate {
            get {
                return ResourceManager.GetString("DateCantBePastTheTaskCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is empty!.
        /// </summary>
        public static string DateIsEmpty {
            get {
                return ResourceManager.GetString("DateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline is empty!.
        /// </summary>
        public static string DeadlineIsEmpty {
            get {
                return ResourceManager.GetString("DeadlineIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline has to be atleast more than 24 hours away from the current time!.
        /// </summary>
        public static string DeadlineMoreThan24Hours {
            get {
                return ResourceManager.GetString("DeadlineMoreThan24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string DoneTasks {
            get {
                return ResourceManager.GetString("DoneTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration can&apos;t be higher than 12 hours!.
        /// </summary>
        public static string DurationCantBeHigher12Hours {
            get {
                return ResourceManager.GetString("DurationCantBeHigher12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration can&apos;t be lower than 0!.
        /// </summary>
        public static string DurationCantBeLowerZero {
            get {
                return ResourceManager.GetString("DurationCantBeLowerZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration on tasks.
        /// </summary>
        public static string DurationOnTasks {
            get {
                return ResourceManager.GetString("DurationOnTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email2 doesn&apos;t match with Email!.
        /// </summary>
        public static string Email2DoesntMatch {
            get {
                return ResourceManager.GetString("Email2DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email2 is empty!.
        /// </summary>
        public static string Email2IsEmpty {
            get {
                return ResourceManager.GetString("Email2IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty!.
        /// </summary>
        public static string EmailIsEmpty {
            get {
                return ResourceManager.GetString("EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email!.
        /// </summary>
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailWithColon {
            get {
                return ResourceManager.GetString("EmailWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can&apos;t be more than 100 characters!.
        /// </summary>
        public static string EmailWrongLength {
            get {
                return ResourceManager.GetString("EmailWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the list to an Excel file.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is empty!.
        /// </summary>
        public static string FirstNameIsEmpty {
            get {
                return ResourceManager.GetString("FirstNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName needs to be one word that contains only letters of the alphabet!.
        /// </summary>
        public static string FirstNameNoNumbers {
            get {
                return ResourceManager.GetString("FirstNameNoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName:.
        /// </summary>
        public static string FirstNameWithColon {
            get {
                return ResourceManager.GetString("FirstNameWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName have to reach minimum 3 characters and also can&apos;t be more than 45!.
        /// </summary>
        public static string FirstNameWrongLength {
            get {
                return ResourceManager.GetString("FirstNameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUNGARY.
        /// </summary>
        public static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is empty!.
        /// </summary>
        public static string LastNameIsEmpty {
            get {
                return ResourceManager.GetString("LastNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName needs to be one word that contains only letters of the alphabet!.
        /// </summary>
        public static string LastNameNoNumbers {
            get {
                return ResourceManager.GetString("LastNameNoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName:.
        /// </summary>
        public static string LastNameWithColon {
            get {
                return ResourceManager.GetString("LastNameWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName have to reach minimum 3 characters and also can&apos;t be more than 45!.
        /// </summary>
        public static string LastNameWrongLength {
            get {
                return ResourceManager.GetString("LastNameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password!.
        /// </summary>
        public static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill your missing profile datas!.
        /// </summary>
        public static string MissingProfileDatasMessage {
            get {
                return ResourceManager.GetString("MissingProfileDatasMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My.
        /// </summary>
        public static string My {
            get {
                return ResourceManager.GetString("My", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PROFILE.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my own records.
        /// </summary>
        public static string MyRecordsCheckBoxMessage {
            get {
                return ResourceManager.GetString("MyRecordsCheckBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my own tasks.
        /// </summary>
        public static string MyTasksCheckBoxMessage {
            get {
                return ResourceManager.GetString("MyTasksCheckBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to choose a Task for the record!.
        /// </summary>
        public static string NeedToChooseTaskForRecord {
            get {
                return ResourceManager.GetString("NeedToChooseTaskForRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to choose a User for the task!.
        /// </summary>
        public static string NeedToChooseUserForTask {
            get {
                return ResourceManager.GetString("NeedToChooseUserForTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task!.
        /// </summary>
        public static string NotificationNewTask {
            get {
                return ResourceManager.GetString("NotificationNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the notifications for the tasks.
        /// </summary>
        public static string NotificationsCheckBoxMessage {
            get {
                return ResourceManager.GetString("NotificationsCheckBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been updated! Deadline has changed!.
        /// </summary>
        public static string NotificationTaskDeadlineChanged {
            get {
                return ResourceManager.GetString("NotificationTaskDeadlineChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been updated! Description has changed!.
        /// </summary>
        public static string NotificationTaskDescriptionChanged {
            get {
                return ResourceManager.GetString("NotificationTaskDescriptionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been updated! Description and Deadline has changed!.
        /// </summary>
        public static string NotificationTaskDescriptionDeadlineChanged {
            get {
                return ResourceManager.GetString("NotificationTaskDescriptionDeadlineChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been Done!.
        /// </summary>
        public static string NotificationTaskDone {
            get {
                return ResourceManager.GetString("NotificationTaskDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is InProgress!.
        /// </summary>
        public static string NotificationTaskInProgress {
            get {
                return ResourceManager.GetString("NotificationTaskInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been updated! Title has changed!.
        /// </summary>
        public static string NotificationTaskTitleChanged {
            get {
                return ResourceManager.GetString("NotificationTaskTitleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been updated! Title and Deadline has changed!.
        /// </summary>
        public static string NotificationTaskTitleDeadlineChanged {
            get {
                return ResourceManager.GetString("NotificationTaskTitleDeadlineChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been updated! Title and Description has changed!.
        /// </summary>
        public static string NotificationTaskTitleDescriptionChanged {
            get {
                return ResourceManager.GetString("NotificationTaskTitleDescriptionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been updated! Title and Description and Deadline has changed!.
        /// </summary>
        public static string NotificationTaskTitleDescriptionDeadlineChanged {
            get {
                return ResourceManager.GetString("NotificationTaskTitleDescriptionDeadlineChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password2 doesn&apos;t match with Password!.
        /// </summary>
        public static string Password2DoesntMatch {
            get {
                return ResourceManager.GetString("Password2DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password2 is empty!.
        /// </summary>
        public static string Password2IsEmpty {
            get {
                return ResourceManager.GetString("Password2IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty!.
        /// </summary>
        public static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password needs to be one word!.
        /// </summary>
        public static string PasswordOneWord {
            get {
                return ResourceManager.GetString("PasswordOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordWithColon {
            get {
                return ResourceManager.GetString("PasswordWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password have to reach minimum 6 characters and also can&apos;t be more than 45!.
        /// </summary>
        public static string PasswordWrongLength {
            get {
                return ResourceManager.GetString("PasswordWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFILE.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        public static string RecordDeleteQuestion {
            get {
                return ResourceManager.GetString("RecordDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORDS.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTER.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the list.
        /// </summary>
        public static string ResetList {
            get {
                return ResourceManager.GetString("ResetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search from the list.
        /// </summary>
        public static string SearchButtonMessage {
            get {
                return ResourceManager.GetString("SearchButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error!.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent time.
        /// </summary>
        public static string SpentTime {
            get {
                return ResourceManager.GetString("SpentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent time on .
        /// </summary>
        public static string SpentTimeMessage1 {
            get {
                return ResourceManager.GetString("SpentTimeMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  task: .
        /// </summary>
        public static string SpentTimeMessage2 {
            get {
                return ResourceManager.GetString("SpentTimeMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status cannot be &quot;Created&quot; when there is recods for the task!.
        /// </summary>
        public static string StatusCannotBeCreatedWithRecords {
            get {
                return ResourceManager.GetString("StatusCannotBeCreatedWithRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status cannot be &quot;Done&quot; when there is no recods for the task!.
        /// </summary>
        public static string StatusCannotBeDoneWithNoRecords {
            get {
                return ResourceManager.GetString("StatusCannotBeDoneWithNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string StatusWithColon {
            get {
                return ResourceManager.GetString("StatusWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtracts 10 minutes from the duration.
        /// </summary>
        public static string Subtract10MinFromDuration {
            get {
                return ResourceManager.GetString("Subtract10MinFromDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        public static string TaskDeleteQuestion1 {
            get {
                return ResourceManager.GetString("TaskDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  task?.
        /// </summary>
        public static string TaskDeleteQuestion2 {
            get {
                return ResourceManager.GetString("TaskDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task recording durations.
        /// </summary>
        public static string TaskRecordingDurations {
            get {
                return ResourceManager.GetString("TaskRecordingDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKS.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone is empty!.
        /// </summary>
        public static string TelephoneIsEmpty {
            get {
                return ResourceManager.GetString("TelephoneIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid telephone number!.
        /// </summary>
        public static string TelephoneIsInvalid {
            get {
                return ResourceManager.GetString("TelephoneIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone:.
        /// </summary>
        public static string TelephoneWithColon {
            get {
                return ResourceManager.GetString("TelephoneWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is empty!.
        /// </summary>
        public static string TitleIsEmpty {
            get {
                return ResourceManager.GetString("TitleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can&apos;t be more than 45 characters!.
        /// </summary>
        public static string TitleWrongLength {
            get {
                return ResourceManager.GetString("TitleWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO DO.
        /// </summary>
        public static string ToDoTasks {
            get {
                return ResourceManager.GetString("ToDoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        public static string UserDeleteQuestion1 {
            get {
                return ResourceManager.GetString("UserDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  user?.
        /// </summary>
        public static string UserDeleteQuestion2 {
            get {
                return ResourceManager.GetString("UserDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  already exists!.
        /// </summary>
        public static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is empty!.
        /// </summary>
        public static string UsernameIsEmpty {
            get {
                return ResourceManager.GetString("UsernameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username needs to be one word!.
        /// </summary>
        public static string UsernameOneWord {
            get {
                return ResourceManager.GetString("UsernameOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string UsernameProfile {
            get {
                return ResourceManager.GetString("UsernameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string UsernameWithColon {
            get {
                return ResourceManager.GetString("UsernameWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username have to reach minimum 6 characters and also can&apos;t be more than 45!.
        /// </summary>
        public static string UsernameWrongLength {
            get {
                return ResourceManager.GetString("UsernameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USERS.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string UserWithColon {
            get {
                return ResourceManager.GetString("UserWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
