//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheet.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceHUN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHUN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeSheet.Resource.ResourceHUN", typeof(ResourceHUN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktív feladatok.
        /// </summary>
        internal static string ActiveTasks {
            get {
                return ResourceManager.GetString("ActiveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vissza.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosít.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A két cég név nem egyezik egymással!.
        /// </summary>
        internal static string CompanyName2DoesntMatch {
            get {
                return ResourceManager.GetString("CompanyName2DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég nevét megerősítő mező üres!.
        /// </summary>
        internal static string CompanyName2IsEmpty {
            get {
                return ResourceManager.GetString("CompanyName2IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég nevének mezője üres!.
        /// </summary>
        internal static string CompanyNameIsEmpty {
            get {
                return ResourceManager.GetString("CompanyNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cég neve legalább 10 és legfeljebb 60 karakter lehet!.
        /// </summary>
        internal static string CompanyNameWrongLength {
            get {
                return ResourceManager.GetString("CompanyNameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum nem lehet későbbi a mai napnál!.
        /// </summary>
        internal static string DateCantBeInFuture {
            get {
                return ResourceManager.GetString("DateCantBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum nem lehet a feladat létrehozásának dátumánál korább!.
        /// </summary>
        internal static string DateCantBePastTheTaskCreationDate {
            get {
                return ResourceManager.GetString("DateCantBePastTheTaskCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dátum mezeje üres!.
        /// </summary>
        internal static string DateIsEmpty {
            get {
                return ResourceManager.GetString("DateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Határidő.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Határidő mezeje üres!.
        /// </summary>
        internal static string DeadlineIsEmpty {
            get {
                return ResourceManager.GetString("DeadlineIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A határidőnek legalább 24 órával később kell lennie mint a jelenlegi idő!.
        /// </summary>
        internal static string DeadlineMoreThan24Hours {
            get {
                return ResourceManager.GetString("DeadlineMoreThan24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törlés.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leírás.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kész feladatok.
        /// </summary>
        internal static string DoneTasks {
            get {
                return ResourceManager.GetString("DoneTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időtartam.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időtartam nem lehet több 12 óránál!.
        /// </summary>
        internal static string DurationCantBeHigher12Hours {
            get {
                return ResourceManager.GetString("DurationCantBeHigher12Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Időtartam nem lehet kisebb 0-nál!.
        /// </summary>
        internal static string DurationCantBeLowerZero {
            get {
                return ResourceManager.GetString("DurationCantBeLowerZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A két email nem egyezik egymással!.
        /// </summary>
        internal static string Email2DoesntMatch {
            get {
                return ResourceManager.GetString("Email2DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailt megerősítő mező üres!.
        /// </summary>
        internal static string Email2IsEmpty {
            get {
                return ResourceManager.GetString("Email2IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email mezeje üres!.
        /// </summary>
        internal static string EmailIsEmpty {
            get {
                return ResourceManager.GetString("EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helytelen email!.
        /// </summary>
        internal static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email legalább 11 és legfeljebb 100 karakter lehet!.
        /// </summary>
        internal static string EmailWrongLength {
            get {
                return ResourceManager.GetString("EmailWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresztnév.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresztnév mezeje üres!.
        /// </summary>
        internal static string FirstNameIsEmpty {
            get {
                return ResourceManager.GetString("FirstNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresztnév nem tartalmazhat betűkön kívül más karaktereket!.
        /// </summary>
        internal static string FirstNameNoNumbers {
            get {
                return ResourceManager.GetString("FirstNameNoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresztnév legalább 3 és legfeljebb 45 karakter lehet!.
        /// </summary>
        internal static string FirstNameWrongLength {
            get {
                return ResourceManager.GetString("FirstNameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Információ.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyelv.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vezetéknév.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vezetéknév mezeje üres!.
        /// </summary>
        internal static string LastNameIsEmpty {
            get {
                return ResourceManager.GetString("LastNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vezetéknév nem tartalmazhat betűkön kívül más karaktereket!.
        /// </summary>
        internal static string LastNameNoNumbers {
            get {
                return ResourceManager.GetString("LastNameNoNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vezetéknév legalább 3 és legfeljebb 45 karakter lehet!.
        /// </summary>
        internal static string LastNameWrongLength {
            get {
                return ResourceManager.GetString("LastNameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bejelentkezés.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helytelen a felhasználónév vagy a jelszó!.
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijelentkezés.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy ki akar jelentkezni?.
        /// </summary>
        internal static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilom.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítéseim.
        /// </summary>
        internal static string MyRecords {
            get {
                return ResourceManager.GetString("MyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feladataim.
        /// </summary>
        internal static string MyTasks {
            get {
                return ResourceManager.GetString("MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kell választani egy feladatot a rögzítéshez!.
        /// </summary>
        internal static string NeedToChooseTaskForRecord {
            get {
                return ResourceManager.GetString("NeedToChooseTaskForRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kell választani egy felhasználot a feladathoz!.
        /// </summary>
        internal static string NeedToChooseUserForTask {
            get {
                return ResourceManager.GetString("NeedToChooseUserForTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új feladat.
        /// </summary>
        internal static string NewTask {
            get {
                return ResourceManager.GetString("NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A két jelszó nem egyezik egymással!.
        /// </summary>
        internal static string Password2DoesntMatch {
            get {
                return ResourceManager.GetString("Password2DoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszót megerősítő mező üres!.
        /// </summary>
        internal static string Password2IsEmpty {
            get {
                return ResourceManager.GetString("Password2IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó mezeje üres!.
        /// </summary>
        internal static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszónak egy szónak kell lennie!.
        /// </summary>
        internal static string PasswordOneWord {
            get {
                return ResourceManager.GetString("PasswordOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó legalább 6 és legfeljebb 45 karakter lehet!.
        /// </summary>
        internal static string PasswordWrongLength {
            get {
                return ResourceManager.GetString("PasswordWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítés.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres rögzítés!.
        /// </summary>
        internal static string RecordCreatedMessage {
            get {
                return ResourceManager.GetString("RecordCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítés sikeresen törölve!.
        /// </summary>
        internal static string RecordDeletedMessage {
            get {
                return ResourceManager.GetString("RecordDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos törölni akarja ezt a rögzítés?.
        /// </summary>
        internal static string RecordDeleteQuestion {
            get {
                return ResourceManager.GetString("RecordDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítések.
        /// </summary>
        internal static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rögzítés sikeresen módosítva!.
        /// </summary>
        internal static string RecordUpdatedMessage {
            get {
                return ResourceManager.GetString("RecordUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frissít.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztrál.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regisztráció.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ment.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keresés.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerver hiba!.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz nem lehet &quot;Created&quot;, ha vannak a feladathoz rögzítések!.
        /// </summary>
        internal static string StatusCannotBeCreatedWithRecords {
            get {
                return ResourceManager.GetString("StatusCannotBeCreatedWithRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Státusz nem lehet &quot;Done&quot;, ha nincs a feladathoz rögzítés!.
        /// </summary>
        internal static string StatusCannotBeDoneWithNoRecords {
            get {
                return ResourceManager.GetString("StatusCannotBeDoneWithNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feladat.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feladat sikeresen létrehozva!.
        /// </summary>
        internal static string TaskCreatedMessage {
            get {
                return ResourceManager.GetString("TaskCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feladat sikeresen törölve!.
        /// </summary>
        internal static string TaskDeletedMessage {
            get {
                return ResourceManager.GetString("TaskDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy törölni akarja .
        /// </summary>
        internal static string TaskDeleteQuestion1 {
            get {
                return ResourceManager.GetString("TaskDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  feladatot?.
        /// </summary>
        internal static string TaskDeleteQuestion2 {
            get {
                return ResourceManager.GetString("TaskDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feladatok.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feladat sikeresn módosítva!.
        /// </summary>
        internal static string TaskUpdatedMessage {
            get {
                return ResourceManager.GetString("TaskUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonszám.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonszám mezeje üres!.
        /// </summary>
        internal static string TelephoneIsEmpty {
            get {
                return ResourceManager.GetString("TelephoneIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helytelen telefonszám!.
        /// </summary>
        internal static string TelephoneIsInvalid {
            get {
                return ResourceManager.GetString("TelephoneIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím mezeje üres!.
        /// </summary>
        internal static string TitleIsEmpty {
            get {
                return ResourceManager.GetString("TitleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cím nem lehet 45 karakternél hosszabb!.
        /// </summary>
        internal static string TitleWrongLength {
            get {
                return ResourceManager.GetString("TitleWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elvégzendő feladatok.
        /// </summary>
        internal static string ToDoTasks {
            get {
                return ResourceManager.GetString("ToDoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó sikeresen létrehozva!.
        /// </summary>
        internal static string UserCreatedMessage {
            get {
                return ResourceManager.GetString("UserCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó sikeresen törölve!.
        /// </summary>
        internal static string UserDeletedMessage {
            get {
                return ResourceManager.GetString("UserDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biztos, hogy törölni akarja .
        /// </summary>
        internal static string UserDeleteQuestion1 {
            get {
                return ResourceManager.GetString("UserDeleteQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  felhasználót?.
        /// </summary>
        internal static string UserDeleteQuestion2 {
            get {
                return ResourceManager.GetString("UserDeleteQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  már létezeik!.
        /// </summary>
        internal static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév mezeje üres!.
        /// </summary>
        internal static string UsernameIsEmpty {
            get {
                return ResourceManager.GetString("UsernameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónévnek egy szónak kell lennie!.
        /// </summary>
        internal static string UsernameOneWord {
            get {
                return ResourceManager.GetString("UsernameOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév legalább 6 és legfeljebb 45 karakter lehet!.
        /// </summary>
        internal static string UsernameWrongLength {
            get {
                return ResourceManager.GetString("UsernameWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználó sikeresen módosítva!.
        /// </summary>
        internal static string UserUpdatedMessage {
            get {
                return ResourceManager.GetString("UserUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figyelmeztetés!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
